version: '2'
services:
  rethinkdb:
    image: rethinkdb:2.4.0
    ports:
      - "28015:28015"
    volumes:
      - ${PWD}/data:/data
    command: rethinkdb --bind all
  app:
    build: .
    command: npm start
    depends_on:
      - rethinkdb
    environment:
      - DB_HOST=rethinkdb
      - NODE_ENV=production
    ports:
      - 9700:9700